#meat
    red_meat_values = ['beef', 'hamburger', 'steak', 'veal', 'bison', 'buffalo', 'lamb', 'mutton', 'goat', 'venison', 'deer', 'elk', 'caribou', 'moose']
    pork_values = ['pork', 'boar', 'pig', 'bratwurst', 'italian sausage', 'ham']
    poultry_values = ['chicken', 'turkey']
    game_values = ['duck', 'pheasant', 'rabbit', 'quail', 'lapin', 'goose', 'grouse']
    cured_meats_values = ['charcuterie', 'salumi','bacon', 'pancetta', 'mortadella', 'salami', 'pepperoni', 'pancetta', 'guanciale', 'capocollo', 'soppressata', 'pastrami', 'jamon iberico', 'bresaola', 'nduja', 'jamon serrano']
    fish_values = ['salmon', 'tuna', 'trout', 'bass', 'seabass', 'snapper', 'cod', 'steelhead', 'yellowtail', 'hamachi', 'kampachi', 'amberjack', 'yellowjack', 'yellow jack', 'tilapia', 'mahi-mahi', 'flounder', 'halibut', 'swordfish', 'anchovy', 'sardine', 'catfish', 'grouper', 'haddock', 'mackerel', 'perch', 'whitefish', 'white fish', 'smelt']
    shellfish_values = ['crab', 'lobster', 'crawfish', 'crayfish', 'langostino', 'shrimp', 'prawn', 'dungeness']
    mollusk_values = ['oyster', 'cuttlefish', 'clam', 'scallop', 'octopus', 'squid', 'conch', 'mussel', 'periwinkle']
    #herb
    fresh_green_values = ['cilantro', 'basil', 'thai basil', 'mint', 'chervil', 'peppermint', 'borage', 'chamomile']
    earthy_green_values = ['parsley', 'oregano', 'thyme', 'tarragon', 'marjoram', 'dill']
    bitter_floral_values = ['sage', 'rosemary', 'lavender', 'bay leaf', 'pine', 'fir']
    allium_spice_values = ['garlic', 'onion', 'scallion', 'chive', 'shallot', 'leek']
    savory_brown_values = ['coriander', 'cumin', 'caraway', 'curry powder']
    sharp_spicy_values = ['mustard', 'horseradish', 'szechuan pepper', 'wasabi']
    perfumed_citrus_spicy_values = ['ginger', 'sorrel', 'galangal', 'turmeric', 'cardamom', 'saffron']
    smokey_spicy_values = ['paprika', 'cayenne pepper', 'chili powder', 'chili pepper', 'ancho pepper', 'chili flakes', 'ancho chili', 'alleppo pepper', 'adobo', 'chipotle', 'chilpotle']
    umami_spicy_values = ['white pepper', 'pink pepper', 'black pepper', 'green pepper', 'white peppercorn', 'pink peppercorn', 'black peppercorn', 'green peppercorn', 'soy sauce', 'olive']
    baking_spice_values = ['cinnamon', 'clove', 'allspice', 'fenugreek', 'vanilla', 'nutmeg']
    anise_values = ['anise', 'licorice', 'star anise', 'fennel', 'celery']
    #cheese
    fresh_salty_values = ['goat cheese', 'chevre', 'feta', 'cotilla', 'queso fresco', 'oaxaca', 'halloumi',  'fromage blanc', 'cottage cheese', 'sour cream', 'paneer']
    delicate_nutty_values = ['brie', 'comte', 'comté', 'gruyere', 'havarti', 'mascarpone', 'mozzarella', 'creme fraiche', 'crème fraîche','ricotta', 'mascarpone', 'swiss cheese', 'emmental', 'raclette', 'colby', 'jack cheese', 'provolone', 'burrata', 'triple cream', 'morbier', 'camembert', 'boursin', 'fontina']
    strong_firm_values = ['asiago', 'cheddar', 'gouda', 'manchego', 'parmesan', 'pecorino', 'cheshire', 'cantal', 'munster', 'parmagiano', 'iberico cheese', 'queso iberico', 'quexo iberico', 'idiazabal']
    pungent_values = ['blue cheese', 'epoisses', 'époisses', 'gorgonzola', 'roquefort', 'stilton', 'taleggio', 'valdeon']
    #prep
    grilled_barbequed_values = ['grilled', 'grill', 'barbeque', 'bbq', 'barbequed', 'bbqd']
    roasted_values = ['roast', 'roasted', 'bake', 'baked']
    smoked_values = ['smoke', 'smoked']
    poached_steamed_values = ['poach', 'poached', 'steam', 'steamed', 'boil', 'boiled']
    sauteed_fried_values = ['sautee', 'sautée', 'sauteed', 'sautéed', 'fried', 'fry', 'sear', 'pan-fry', 'pan-fried', 'pan-sear', 'pan-seared', 'sear', 'seared', 'deep-fry']
    #veg
    green_veg_values = ['lettuce', 'cabbage', 'spinach', 'kale', 'watercress', 'brussels sprout', 'zucchini', 'okra', 'asparagus', 'artichoke', 'cucumber', 'collard', 'chard', 'green bean', 'endive', 'broccolini', 'avocado', 'romanesco', 'cauliflower']
    root_veg_values = ['sweet potato', 'squash', 'pumpkin', 'carrot', 'turnip', 'beet', 'radish', 'parsnip', 'daikon', 'rutabaga', 'salsify', 'yam', 'yuca', 'yucca', 'butternut', 'gourd']
    allium_values = ['onion', 'garlic', 'shallot', 'chive', 'scallion', 'leek', 'ramps']
    nightshade_values = ['potato', 'bell pepper', 'tomato', 'eggplant', 'tomatillo']
    hot_pepper_values = ['jalapeno', 'habanero', 'birdseye', 'thai chili', 'chili pepper']
    bean_values = ['bean', 'chickpea', 'lentil', 'edamame', 'pea']
    fungi_values = ['mushroom', 'chantarelle', 'shitake', 'crimini', 'cremini', 'oyster mushroom', 'porcini', 'maitake', 'portobello', 'champignon', 'boletus', 'hen of the woods', 'truffle']